version: '3.3'
services:
  backend:
    image: dto80/234-lab11:latest
    ports:
      - "8089:8080"
    volumes:
      - type: bind
        source: /home/ubuntu/auto/excel
        target: /data
  frontend:
    image: little0011/automated-test:latest
    ports:
      - "8088:80"